# Generated by Django 5.0.7 on 2025-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_is_best_seller_dish_is_new_dish_is_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('beverages', 'Coffee/Tea'), ('snacks', 'Snacks'), ('meals', 'Meals'), ('desserts', 'Desserts')], default='meals', max_length=20),
        ),
    ]
