# Generated by Django 5.0.7 on 2025-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode_prefix', models.CharField(help_text='First 3-6 digits of PIN', max_length=6)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('eta_min', models.PositiveIntegerField(default=30)),
                ('eta_max', models.PositiveIntegerField(default=45)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
